Logging:
  LogLevel:
    Default: Information
    Microsoft: Warning

ConnectionStrings:
  DefaultConnection: "Server=host.docker.internal,1433;Database=poc_bas;User Id=sa;Password=TuPasswordFuerte123!;TrustServerCertificate=True;Encrypt=False"

MongoDb:
  ConnectionString: "mongodb://host.docker.internal:27017"
  DatabaseName: "poc_bas"
  TenantsCollectionName: "tenants"

CORS_Origins: "http://localhost:3000" 
