apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-back                # Nuevo nombre del deployment 
  namespace: develop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platform-back            # Nuevo label de app
  template:
    metadata: 
      labels:
        app: platform-back           # Nuevo label de app
    spec:
      containers:
        - name: webui           # Este puede quedar igual si el container se llama así
          image: developmentzarcom/webui:latest
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT  
              value: "Development"
---
apiVersion: v1
kind: Service
metadata:
  name: platform-back-service        # Nuevo nombre del service
  namespace: develop
spec:
  type: NodePort
  selector:
    app: platform-back               # El selector tiene que coincidir con el label de arriba
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 3111